apiVersion: apps/v1
kind: Deployment
metadata:
  name: suscripciones-backend
  namespace: default
  labels:
    app: suscripciones-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suscripciones-backend
  template:
    metadata:
      labels:
        app: suscripciones-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: suscripciones-api
          image: ECR_IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"