apiVersion: v1
kind: Service
metadata:
  name: suscripciones-backend-service
  namespace: default
  labels:
    app: suscripciones-backend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: suscripciones-backend