name: "CI/CD: Quality Gates, Build and Deploy to AWS ECS"

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-validate-deploy:
    name: "Verify Quality & Deploy to AWS"
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: "Set up JDK 21"
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: "SonarQube Scan & Compliance Check"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=TheRexInformatics_ingdevops_ev3 \
            -Dsonar.organization=therexinformatics \
            -Dsonar.host.url=https://sonarcloud.io

      - name: "Quality Gate Break Check"
        uses: sonarsource/sonarqube-quality-gate-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          scanMetadataReportFile: target/sonar/report-task.txt
        timeout-minutes: 5

      - name: "Configurar credenciales AWS"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: "Login en Amazon ECR"
        uses: aws-actions/amazon-ecr-login@v2

      - name: "Build imagen Backend y push a ECR"
        run: |
          docker build -t suscripciones-backend .
          docker tag suscripciones-backend:latest 093239445247.dkr.ecr.us-east-1.amazonaws.com/suscripciones-backend:latest
          docker push 093239445247.dkr.ecr.us-east-1.amazonaws.com/suscripciones-backend:latest

      - name: "Forzar despliegue en el Servicio ECS"
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.ECS_SERVICE_NAME }} \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }}

      - name: "Finalización Exitosa"
        run: echo "🚀 Imagen enviada y actualización de servicio forzada en AWS ECS"