name: Deploy to Amazon EKS

on:
  push:
    branches: [ "main" ] 

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: eks-cluster-ev3
  ECR_REPOSITORY: ev-devops3

jobs:
  deploy:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        # 1. Construye la imagen Docker localmente usando el archivo Dockerfile de la raíz
        docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
        
        # 2. Sube la imagen empaquetada a tu repositorio privado de AWS ECR
        docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

    - name: Update kubeconfig for EKS
      run: |
        # Configura las credenciales de la máquina virtual de GitHub para interactuar con tu Kubernetes en AWS
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

    - name: Deploy to EKS
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        # Reemplaza la etiqueta temporal ECR_IMAGE_PLACEHOLDER en tu deployment.yml por la ruta real de AWS ECR
        sed -i "s|ECR_IMAGE_PLACEHOLDER|$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest|g" k8s/deployment.yml
        
        # Aplica los manifiestos en el namespace 'default' del clúster orquestado
        kubectl apply -f k8s/deployment.yml
        kubectl apply -f k8s/service.yml